# Generated by Django 3.1.7 on 2022-01-26 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Kurs')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=512)),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['create_date']},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='auto_add',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='miniature',
            field=models.ImageField(default='lekcja.png', upload_to='profile', verbose_name='Miniatura'),
        ),
        migrations.AddField(
            model_name='test',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='tests', verbose_name='Zdjęcie'),
        ),
        migrations.AddField(
            model_name='test',
            name='option1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='question',
            field=models.TextField(default='', verbose_name='Pytanie'),
        ),
        migrations.AddField(
            model_name='test',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nazwa lekcji'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nazwa testu'),
        ),
        migrations.DeleteModel(
            name='Answear',
        ),
        migrations.AddField(
            model_name='comment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.lesson'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elearn.category'),
        ),
    ]
