# Generated by Django 3.1.7 on 2022-01-17 18:40

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='miniature',
            field=models.ImageField(default='lekcja.png', upload_to='profile', verbose_name='Miniatura'),
        ),
        migrations.AddField(
            model_name='test',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='tests', verbose_name='Zdjęcie'),
        ),
        migrations.AddField(
            model_name='test',
            name='option1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='question',
            field=models.TextField(default='', verbose_name='Pytanie'),
        ),
        migrations.AddField(
            model_name='test',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nazwa lekcji'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nazwa testu'),
        ),
        migrations.DeleteModel(
            name='Answear',
        ),
    ]
