# Generated by Django 3.1.7 on 2022-02-06 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
                ('body', models.TextField(max_length=512, verbose_name='komentarz')),
            ],
            options={
                'verbose_name': 'Komentarz',
                'verbose_name_plural': 'Komentarze',
            },
        ),
        migrations.RemoveField(
            model_name='learner',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='takentest',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='takentest',
            name='test',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['create_date'], 'verbose_name': 'Lekcja', 'verbose_name_plural': 'Lekcje'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Testy'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='auto_add',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='miniature',
            field=models.ImageField(default='lekcja.png', upload_to='', verbose_name='Miniatura'),
        ),
        migrations.AddField(
            model_name='test',
            name='answer',
            field=models.CharField(max_length=200, null=True, verbose_name='Poprawna odpowiedź'),
        ),
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='tests', verbose_name='Zdjęcie'),
        ),
        migrations.AddField(
            model_name='test',
            name='option1',
            field=models.CharField(max_length=200, null=True, verbose_name='Odpowiedz 1'),
        ),
        migrations.AddField(
            model_name='test',
            name='option2',
            field=models.CharField(max_length=200, null=True, verbose_name='Odpowiedz 2'),
        ),
        migrations.AddField(
            model_name='test',
            name='option3',
            field=models.CharField(max_length=200, null=True, verbose_name='Odpowiedz 3'),
        ),
        migrations.AddField(
            model_name='test',
            name='option4',
            field=models.CharField(max_length=200, null=True, verbose_name='Odpowiedz 4'),
        ),
        migrations.AddField(
            model_name='test',
            name='question',
            field=models.TextField(default='', verbose_name='Pytanie'),
        ),
        migrations.AddField(
            model_name='test',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='wideo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nazwa lekcji'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nazwa testu'),
        ),
        migrations.AlterField(
            model_name='test',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik'),
        ),
        migrations.DeleteModel(
            name='Answear',
        ),
        migrations.DeleteModel(
            name='Learner',
        ),
        migrations.DeleteModel(
            name='Takentest',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='comment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.lesson', verbose_name='lekcja'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik'),
        ),
    ]
